export const novels = [
  {
    id: 1,
    title: 'A Will Eternal',
    author: 'Ergen',
    filename: 'A-Will-Eternal .epub',
    image: '/novels/images/A-Will-Eternal.png',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1315,
    synopsis: [
      'One will to create oceans. One will to summon the mulberry fields.',
      'One will to slaughter countless devils. One will to eradicate innumerable immortals.',
      'Only my will… is eternal.',
    ],
  },
  {
    id: 2,
    title: 'Douluo Dalu',
    author: '<unknown>',
    filename: 'Douluo-Dalu .epub',
    image: '/novels/images/Douluo-Dalu.jpg',
    description: 'No description available.',
    status: 'Completed',
    chapters: 331,
    synopsis: [
      "Tang Sect, the most famous martial arts sect of all. By stealing its most secret teachings to fulfill his dreams, Tang San committed an unforgivable crime. With his ambition attained, he hands his legacy to the sect and throws himself from the fearsome 'Hell's Peak'.",
      'But he could have never imagined that this would reincarnate him in another world, one without magic, martial arts, and grudges. A land where only the mystical souls of battle lay.',
      'The continent of Douluo.',
      'How will Tang San survive in this unknown environment? With a new road to follow, a new legend begins…',
    ],
  },
  {
    id: 3,
    title: 'Everyone Else is a Returnee',
    author: 'Toika',
    filename: 'Everyone-Else-is-a-Returnee-(360 Chapters).epub',
    image: '/novels/images/Everyone-Else-is-a-Returnee-(360 Chapters).png',
    description: 'No description available.',
    status: 'Completed',
    chapters: 358,
    synopsis: [
      'Left out during elementary school picnic.',
      'Left out during middle school camp.',
      'Left out during high school trip.',
      "I finally became a college student and what? I'm left out from the entire humanity?",
      "Yu IlHan who protects the earth alone while everybody's away in other worlds.",
      'His legend starts after humanity comes back and meets the Great Cataclysm!',
    ],
  },
  // {
  //   id: 4,
  //   title: 'I Shall Seal the Heavens',
  //   author: 'Er Gen',
  //   filename: 'I-Shall-Seal-the-Heavens.epub',
  //   image: '/novels/images/I-Shall-Seal-the-Heavens.webp',
  //   description: 'No description available.',
  //   status: 'Completed',
  //   chapters: 1614,
  //   synopsis: [
  //     "If I want something, the heavens better have it. If I don't want something, it better not exist in the heavens.",
  //     'This is the story of a man who will seal the heavens.',
  //   ],
  // },
  {
    id: 5,
    title: "I'm Really Not The Demon God's Lackey",
    author: 'Great Calamity Of Fire',
    filename: 'IRNTDGL.epub',
    image: '/novels/images/I’m-Really-Not-The-Demon-God’s-Lackey.webp',
    description: 'No description available.',
    status: 'Completed',
    chapters: 500,
    synopsis: [
      'Lin Jie, a transmigrator, is the owner of a bookstore in another world. He sells books that can greatly influence the world.',
      'However, his customers think he is a powerful being who hides his true strength and intentions.',
    ],
  },
  {
    id: 6,
    title: 'Lightning Is the Only Way',
    author: 'Warmisch',
    filename: 'Lightning-is-the-only-way.epub',
    image: '/novels/images/Lightning-is-the-only-way.jpg',
    description: 'No description available.',
    status: 'Completed',
    chapters: 800,
    synopsis: [
      'Gravis, a young man from Earth, is transported to a world where strength reigns supreme.',
      'With the power of lightning, he must navigate this new world and become the strongest.',
    ],
  },
  {
    id: 7,
    title: 'Lord of the Mysteries',
    author: 'Cuttlefish That Loves Diving',
    filename: 'Lord-of-the-Mysteries.epub',
    image: '/novels/images/Lord-of-the-Mysteries.webp',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1394,
    synopsis: [
      'With the rising tide of steam power and machinery, who can come close to being a Beyonder?',
      'The light of the Fourth Epoch has yet to fade, and the glory of the Fifth Epoch is emerging.',
    ],
  },
  {
    id: 8,
    title: 'Nightfall',
    author: '<unknown>',
    filename: 'Nightfall.epub',
    image: '/novels/images/Nightfall.jpg',
    description: 'No description available.',
    status: 'Ongoing',
    chapters: 1000,
    synopsis: [
      'Chang An, the capital of Tang, is the most prosperous city in the world.',
      'Ning Que, a young man, enters the city and begins his journey to uncover the secrets of the world.',
    ],
  },
  {
    id: 9,
    title: 'Release That Witch',
    author: '<unknown>',
    filename: 'Release-that-witch.epub',
    image: '/novels/images/Release-that-witch.jpg',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1498,
    synopsis: [
      'A modern-day engineer is transmigrated to a medieval world and becomes a prince.',
      'With his knowledge of engineering, he must lead his people to prosperity and fight against the church.',
    ],
  },
  {
    id: 10,
    title: 'Reverend Insanity',
    author: 'Gu Zhen Ren, 蛊真人',
    filename: 'Reverend-Insanity.epub',
    image: '/novels/images/Reverend-Insanity.webp',
    description: 'No description available.',
    status: 'Ongoing',
    chapters: 2327,
    synopsis: [
      'A demon is born in the world. A demon is born in the heart.',
      'A story of a man who seeks immortality and power, no matter the cost.',
    ],
  },
  {
    id: 11,
    title: 'The Dark King',
    author: 'Ancient Xi',
    filename: 'The-Dark-King.epub',
    image: '/novels/images/The-Dark-King.jpg',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1279,
    synopsis: [
      'Civilization is destroyed and records lost. Only Dudian survives in a cryogenic sleep. Three hundred years later, Dudian wakes up and must become Dean to survive. Who can he trust in this world overrun by monsters without and within?',
    ],
  },
  {
    id: 12,
    title: 'The Desolate Era',
    author: 'I Eat Tomatoes',
    filename: 'The-Desolate-Era.epub',
    image: '/novels/images/The-Desolate-Era.jpeg',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1451,
    synopsis: [
      "Fate had never been kind to Ji Ning. Wracked by illnesses and infirm his entire life on Earth, Ji Ning knew early on that he would die as a teenager. What he didn't know was that there really was such a thing as life after death and that the multiverse was a far larger place than he thought.",
      'A lucky twist of fate meant that Ji Ning was reborn into a world of Immortals and monsters, of Ki Refiners and powerful Fiendgods, a world where Dynasties lasted for millions of years. A world which is both greater… and yet also smaller… than he ever could imagine. He would have the opportunity to join them, and in this life, Ji Ning swore to himself, he would never let himself be weak again! The Era he was born into was a Desolate one, but Ji Ning would make it his era.',
    ],
  },
  {
    id: 13,
    title: 'The Legendary Mechanic',
    author: 'Chocolion',
    filename: 'The-Legendary-Mechanic.epub',
    image: '/novels/images/The-Legendary-Mechanic.png',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1464,
    synopsis: [
      'What do you do when you wake up and find yourself inside the very game that you love?',
      'What do you do when you realize you that you have not only become an NPC – you have even been thrown back in time to before the game even launched!',
      "What will happen when our protagonist's two realities coincide?",
      "Han Xiao was a professional power leveler before his transmigration. Using his past life's knowledge, Han Xiao sweeps through the universe as he prepares for the arrival of the players. This is definitely not your typical transmigration novel.",
    ],
  },
  {
    id: 14,
    title: 'The Strongest System',
    author: 'Xinfeng',
    filename: 'The-Strongest-System.epub',
    image: '/novels/images/The-Strongest-System.jpg',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1159,
    synopsis: [
      'Yours Truly shall have all of you bow down to me!',
      "Arriving in this brand-new world, Lin Fan found himself in possession of a system which allows him to level up indefinitely unbounded by the limitations of this world. Upon learning a powerful technique of Monkey Steals Peaches, Lin Fan realises that he's poised to literally become the strongest person in this entire world. But of course, how boring would that be unless the whole world gets to know about his great name?",
      'Shameless. Righteous. Smart. Lin Fan will let no one (or balls) stand in his way to glory!',
      'Hilarious for all the wrong reasons and exciting for all the right ones, this novel will definitely have you roaring out in laughter and set your blood pumping all at the same time. Join us in this rollercoaster of a masterpiece with Lin Fan and his trusty sidekicks as he shows the world what it truly means to be YOURS TRULY.',
      "There is a person, whose entire life is a legend. There is a person, whose extraordinariness radiates from his brows There is a person, his name is Lin Fan. Everybody: 'Lin Fan, I want to have your babies.' A dominating life of unrestrained swag needs no explanation.",
    ],
  },
  {
    id: 15,
    title: 'Throne of Magical Arcana',
    author: 'Cuttlefish That Loves Diving',
    filename: 'Throne-of-Magical-Arcana.epub',
    image: '/novels/images/Throne-of-Magical-Arcana.jpg',
    description: 'No description available.',
    status: 'Completed',
    chapters: 800,
    synopsis: [
      'A young man with a mysterious past enters a world of magic and science.',
      'With his unique abilities, he must navigate the complex world of politics and power.',
    ],
  },
  {
    id: 16,
    title: "Trash of the Count's Family",
    author: 'Yoo Ryeo Han',
    filename: "Trash-of-the-Count's-Family-(800 Chapters).epub",
    image: "/novels/images/Trash-of-the-Count's-Family-(800 Chapters).jpg",
    description: 'No description available.',
    status: 'Ongoing',
    chapters: 800,
    synopsis: [
      'When I opened my eyes, I was inside a novel.',
      "The birth of the trash of the Count's family.",
      'But I am not the trash. I am the one who will change the fate of this family.',
    ],
  },
  {
    id: 17,
    title: 'Warlock of the Magus World',
    author: 'The Plagiarist',
    filename: 'Warlock-of-the-Magus-World.epub',
    image: '/novels/images/Warlock-of-the-Magus-World.webp',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1200,
    synopsis: [
      'What happens when a scientist from a futuristic world reincarnates in a World of Magic and Knights?',
      "An awesome MC is born, that's what happens!",
    ],
  },
]
