export const novels = [
  {
    id: 1,
    title: 'A Will Eternal',
    author: 'Ergen',
    filename: 'A-Will-Eternal .epub',
    image: '/novels/images/A-Will-Eternal.png',
    description: 'No description available.',
    status: 'Completed',
    chapters: 1315,
    synopsis: [
      'One will to create oceans. One will to summon the mulberry fields.',
      'One will to slaughter countless devils. One will to eradicate innumerable immortals.',
      'Only my will… is eternal.',
    ],
  },
  {
    id: 2,
    title: 'Douluo Dalu',
    author: '<unknown>',
    filename: 'Douluo-Dalu .epub',
    image: '/novels/images/Douluo-Dalu.png',
    description: 'No description available.',
    status: 'Completed',
    chapters: 331,
    synopsis: [
      "Tang Sect, the most famous martial arts sect of all. By stealing its most secret teachings to fulfill his dreams, Tang San committed an unforgivable crime. With his ambition attained, he hands his legacy to the sect and throws himself from the fearsome 'Hell's Peak'.",
      'But he could have never imagined that this would reincarnate him in another world, one without magic, martial arts, and grudges. A land where only the mystical souls of battle lay.',
      'The continent of Douluo.',
      'How will Tang San survive in this unknown environment? With a new road to follow, a new legend begins…',
    ],
  },
  {
    id: 3,
    title: 'Everyone Else is a Returnee',
    author: 'Toika',
    filename: 'Everyone-Else-is-a-Returnee-(360 Chapters).epub',
    image: '/novels/images/Everyone-Else-is-a-Returnee-(360 Chapters).png',
    description: 'No description available.',
    status: 'Completed',
    chapters: 358,
    synopsis: [
      'Left out during elementary school picnic.',
      'Left out during middle school camp.',
      'Left out during high school trip.',
      "I finally became a college student and what? I'm left out from the entire humanity?",
      "Yu IlHan who protects the earth alone while everybody's away in other worlds.",
      'His legend starts after humanity comes back and meets the Great Cataclysm!',
    ],
  },
  {
    id: 4,
    title: "Kingdom's Bloodline",
    author: 'Masterless Sword',
    filename: "Kingdom's-Bloodline.epub",
    image: "/novels/images/Kingdom's-Bloodline.png",
    description: 'No description available.',
    status: 'Ongoing',
    chapters: 617,
    synopsis: [
      'A lowly child beggar, a noble prince, a monster viewed as the enemy of the entire world. If you possess all three identities at the same time, which identity would you choose to help you earn a better ending?',
      'Thales did not have the answer.',
      'He only knew that he came to a different and magnificent world, and he had to face a future that was as difficult to handle as a nightmare.',
      'The glorious Empire had already been destroyed for one thousand years, the dying royal family suffered many problems, the legendary sacred battle had plenty of conspiracies, the divided world was in chaos.',
      'But Thales had nothing.',
      'The only thing he had left was an unswerving determination to preserve his own identity, bravery which would allow him to survive in a perilous situation, and a belief that he would never submit to principles he did not believe.',
      "A King does not gain respect by virtue of his bloodline. The bloodline's glory rests on the deeds of the King.",
      "Darkness will baptize light. Fire will create true steel. The forbidden prince's story starts here.",
    ],
  },
  {
    id: 5,
    title: 'The Dark King',
    author: 'Ancient Xi',
    filename: 'The-Dark-King.epub',
    image: '/novels/images/The-Dark-King.png',
    status: 'Completed',
    chapters: 1279,
    description: 'No description available.',
    synopsis: [
      'Civilization is destroyed and records lost. Only Dudian survives in a cryogenic sleep. Three hundred years later, Dudian wakes up and must become Dean to survive. Who can he trust in this world overrun by monsters without and within?',
    ],
  },
  {
    id: 6,
    title: 'The Desolate Era (Web Novel)',
    author: 'I Eat Tomatoes',
    filename: 'The-Desolate-Era.epub',
    image: '/novels/images/The-Desolate-Era.png',
    status: 'Completed',
    chapters: 1451,
    description: 'No description available.',
    synopsis: [
      "Fate had never been kind to Ji Ning. Wracked by illnesses and infirm his entire life on Earth, Ji Ning knew early on that he would die as a teenager. What he didn't know was that there really was such a thing as life after death and that the multiverse was a far larger place than he thought.",
      'A lucky twist of fate meant that Ji Ning was reborn into a world of Immortals and monsters, of Ki Refiners and powerful Fiendgods, a world where Dynasties lasted for millions of years. A world which is both greater… and yet also smaller… than he ever could imagine. He would have the opportunity to join them, and in this life, Ji Ning swore to himself, he would never let himself be weak again! The Era he was born into was a Desolate one, but Ji Ning would make it his era.',
    ],
  },
  {
    id: 7,
    title: 'The Legendary Mechanic (WN)',
    author: 'Chocolion',
    filename: 'The-Legendary-Mechanic.epub',
    status: 'Completed',
    chapters: 1464,
    image: '/novels/images/The-Legendary-Mechanic.png',
    description: 'No description available.',
    synopsis: [
      'What do you do when you wake up and find yourself inside the very game that you love?',
      'What do you do when you realize you that you have not only become an NPC – you have even been thrown back in time to before the game even launched!',
      "What will happen when our protagonist's two realities coincide?",
      "Han Xiao was a professional power leveler before his transmigration. Using his past life's knowledge, Han Xiao sweeps through the universe as he prepares for the arrival of the players. This is definitely not your typical transmigration novel.",
    ],
  },
  {
    id: 8,
    title: 'The Strongest System',
    author: 'Xinfeng',
    filename: 'The-Strongest-System.epub',
    image: '/novels/images/The-Strongest-System.png',
    status: 'Completed',
    chapters: 1159,
    description: 'No description available.',
    synopsis: [
      'Yours Truly shall have all of you bow down to me!',
      "Arriving in this brand-new world, Lin Fan found himself in possession of a system which allows him to level up indefinitely unbounded by the limitations of this world. Upon learning a powerful technique of Monkey Steals Peaches, Lin Fan realises that he's poised to literally become the strongest person in this entire world. But of course, how boring would that be unless the whole world gets to know about his great name?",
      'Shameless. Righteous. Smart. Lin Fan will let no one (or balls) stand in his way to glory!',
      'Hilarious for all the wrong reasons and exciting for all the right ones, this novel will definitely have you roaring out in laughter and set your blood pumping all at the same time. Join us in this rollercoaster of a masterpiece with Lin Fan and his trusty sidekicks as he shows the world what it truly means to be YOURS TRULY.',
      "There is a person, whose entire life is a legend. There is a person, whose extraordinariness radiates from his brows There is a person, his name is Lin Fan. Everybody: 'Lin Fan, I want to have your babies.' A dominating life of unrestrained swag needs no explanation.",
    ],
  },
]
